---
- name: SSH Key Generation and Authorization (RHEL 10.1)
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: Ensure root has an Ed25519 SSH key
      ansible.builtin.user:
        name: root
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519
        ssh_key_comment: "root@svc-1.ocp.lan"
      register: ssh_key_result

    - name: Slurp the public key content
      ansible.builtin.slurp:
        src: /root/.ssh/id_ed25519.pub
      register: public_key_raw

    - name: Ensure the key is in authorized_keys (Idempotent Fix)
      ansible.builtin.lineinfile:
        path: /root/.ssh/authorized_keys
        # This regex looks for any line ending with your specific key comment
        regexp: '.*root@svc-1\.ocp\.lan$'
        line: "{{ public_key_raw.content | b64decode | trim }}"
        owner: root
        group: root
        mode: '0600'
        create: yes
      register: auth_result

    - name: Final Status
      ansible.builtin.debug:
        msg: "SSH Key is ready and authorized."
      when: auth_result.changed or ssh_key_result.changed
