---
- name: Force Replace Network Configurations (RHEL 9.7)
  hosts: svc-1.ocp.lan
  become: true
  gather_facts: false

  vars:
    nm_path: "/etc/sysconfig/network-scripts"
    # Path relative to this playbook location
    repo_path: "{{ playbook_dir }}/../config_Files/network-ip"
    network_files:
      - ifcfg-ens160
      - ifcfg-ens192

  tasks:
    - name: Purge existing connection files
      ansible.builtin.file:
        path: "{{ nm_path }}/{{ item }}"
        state: absent
      loop: "{{ network_files }}"

    - name: Deploy corrected RHEL keyfiles
      ansible.builtin.copy:
        src: "{{ repo_path }}/{{ item }}"
        dest: "{{ nm_path }}/{{ item }}"
        owner: root
        group: root
        mode: "0600"
      loop: "{{ network_files }}"
      notify: Restart Networking

  handlers:
    - name: Restart Networking
      ansible.builtin.shell: |
        nmcli connection reload
        nmcli connection up ens160
        nmcli connection up ens192
