---
- name: Force Replace Network Configurations (RHEL 10.1)
  hosts: localhost
  become: true
  gather_facts: false

  vars:
    nm_path: "/etc/NetworkManager/system-connections"
    # Update this path if it is different on your system
    repo_path: "/root/openShift_Cluster_Config/service_Node_Config/service_Node-01/config_Files/network-ip"
    network_files:
      - ens160.nmconnection
      - ens192.nmconnection

  tasks:
    - name: Purge existing connection files
      ansible.builtin.file:
        path: "{{ nm_path }}/{{ item }}"
        state: absent
      loop: "{{ network_files }}"

    - name: Deploy corrected RHEL keyfiles
      ansible.builtin.copy:
        src: "{{ repo_path }}/{{ item }}"
        dest: "{{ nm_path }}/{{ item }}"
        owner: root
        group: root
        mode: "0600"
      loop: "{{ network_files }}"
      notify: Restart Networking

  handlers:
    - name: Restart Networking
      ansible.builtin.shell: |
        nmcli connection reload
        nmcli connection up ens160
        nmcli connection up ens192
