---
- name: Force Replace Network Configurations (RHEL 9.7)
  hosts: svc-1.ocp.lan
  become: true
  gather_facts: false

  vars:
    nm_path: "/etc/sysconfig/network-scripts"
    repo_path: "{{ playbook_dir }}/../config_Files/network-ip"
    network_files:
      - ifcfg-ens160
      - ifcfg-ens192

  tasks:
    # ------------------------------------------------------------------
    # 1. Deploy network config files (authoritative, idempotent)
    # ------------------------------------------------------------------

    - name: Deploy corrected RHEL keyfiles (only overwrite if different)
      ansible.builtin.copy:
        src: "{{ repo_path }}/{{ item }}"
        dest: "{{ nm_path }}/{{ item }}"
        owner: root
        group: root
        mode: "0600"
        backup: true
      loop: "{{ network_files }}"
      notify: Restart Networking

    # ------------------------------------------------------------------
    # 2. Verify zones from NetworkManager (no blind changes)
    # ------------------------------------------------------------------

    - name: Get current zone for ens192
      ansible.builtin.command: nmcli -g connection.zone connection show ens192
      register: ens192_zone
      changed_when: false
      failed_when: false

    - name: Warn if ens192 zone is not internal (should come from ifcfg)
      ansible.builtin.debug:
        msg: "WARNING: ens192 zone is {{ ens192_zone.stdout }}, expected internal"
      when: ens192_zone.stdout != "internal"

    - name: Get current zone for ens160
      ansible.builtin.command: nmcli -g connection.zone connection show ens160
      register: ens160_zone
      changed_when: false
      failed_when: false

    - name: Warn if ens160 zone is not external (should come from ifcfg)
      ansible.builtin.debug:
        msg: "WARNING: ens160 zone is {{ ens160_zone.stdout }}, expected external"
      when: ens160_zone.stdout != "external"

    # ------------------------------------------------------------------
    # 3. Firewalld baseline
    # ------------------------------------------------------------------

    - name: Ensure firewalld is running and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Get current default firewall zone
      ansible.builtin.command: firewall-cmd --get-default-zone
      register: default_zone
      changed_when: false

    - name: Set default firewall zone to internal if needed
      ansible.builtin.command: firewall-cmd --set-default-zone=internal
      when: default_zone.stdout != "internal"
      notify: Reload Firewalld

    # ------------------------------------------------------------------
    # 4. Masquerade (only on external zone — safe & idempotent)
    # ------------------------------------------------------------------

    - name: Check masquerade on external zone
      ansible.builtin.command: firewall-cmd --zone=external --query-masquerade
      register: ext_masq
      changed_when: false
      failed_when: false

    - name: Enable masquerade on external zone if needed (permanent)
      ansible.builtin.command: firewall-cmd --zone=external --add-masquerade --permanent
      when: ext_masq.stdout != "yes"
      notify: Reload Firewalld

    # ------------------------------------------------------------------
    # 5. Verification
    # ------------------------------------------------------------------

    - name: Get active firewall zones
      ansible.builtin.command: firewall-cmd --get-active-zones
      register: active_zones
      changed_when: false

    - name: Print active firewall zones
      ansible.builtin.debug:
        var: active_zones.stdout

    - name: Verify ens192 has IP assigned
      ansible.builtin.command: ip addr show ens192
      register: ens192_ip
      changed_when: false

    - name: Fail if ens192 has no IP
      ansible.builtin.fail:
        msg: "ens192 has no IP address assigned!"
      when: "'inet ' not in ens192_ip.stdout"

  handlers:
    - name: Reload Firewalld
      ansible.builtin.command: firewall-cmd --reload

    - name: Restart Networking
      ansible.builtin.shell: |
        nmcli connection reload
        nmcli con up ifname ens160
        nmcli con up ifname ens192
      changed_when: false
