---
- name: IP Forwarding & NAT Setup (RHEL 9.7 Compatible)
  hosts: svc-1.ocp.lan
  become: true
  gather_facts: false

  vars:
    wan_interface: "ens160"
    lan_interface: "ens192"

  tasks:
    # -------- 1. Enable IP Forwarding (Persistent) --------
    - name: Create sysctl config for IP forwarding
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-ip-forward.conf
        content: "net.ipv4.ip_forward=1"
        owner: root
        group: root
        mode: '0644'

    - name: Apply sysctl settings
      ansible.builtin.command: sysctl -p /etc/sysctl.d/99-ip-forward.conf

    # -------- 2. Configure Firewalld Interfaces & Masquerade --------
    - name: Assign WAN interface to external zone
      ansible.builtin.command: firewall-cmd --permanent --zone=external --add-interface={{ wan_interface }}
      failed_when: false

    - name: Assign LAN interface to internal zone
      ansible.builtin.command: firewall-cmd --permanent --zone=internal --add-interface={{ lan_interface }}
      failed_when: false

    - name: Enable Masquerading on external zone
      ansible.builtin.command: firewall-cmd --permanent --zone=external --add-masquerade
      failed_when: false

    # -------- 3. Forwarding Policy (Explicit Commands) --------
    - name: Create Forwarding Policy
      ansible.builtin.command: firewall-cmd --permanent --new-policy=internalToExternal
      failed_when: false

    - name: Set Policy Ingress Zone
      ansible.builtin.command: firewall-cmd --permanent --policy=internalToExternal --add-ingress-zone=internal
      failed_when: false

    - name: Set Policy Egress Zone
      ansible.builtin.command: firewall-cmd --permanent --policy=internalToExternal --add-egress-zone=external
      failed_when: false

    - name: Set Policy Target to ACCEPT
      ansible.builtin.command: firewall-cmd --permanent --policy=internalToExternal --set-target=ACCEPT
      failed_when: false

    - name: Reload Firewalld
      ansible.builtin.command: firewall-cmd --reload
