---
- name: RHEL 9.7 Keepalived Setup
  hosts: svc-1.ocp.lan
  become: true
  # REQUIRED for ansible_user_dir to work
  gather_facts: true

  vars:
    config_src_base: "{{ ansible_user_dir }}/openShift_Cluster_Config/service_Node_Config/svc-1/config_Files/keepalived"

  tasks:
    - name: Install keepalived
      ansible.builtin.dnf:
        name: keepalived
        state: present

    # Replacing the broken sysctl module with lineinfile
    - name: Configure ip_nonlocal_bind in sysctl.conf
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_nonlocal_bind'
        line: 'net.ipv4.ip_nonlocal_bind = 1'
        state: present
      register: sysctl_file

    - name: Apply sysctl settings if file changed
      ansible.builtin.command: sysctl -p
      when: sysctl_file.changed

    - name: Ensure keepalived config directory exists
      ansible.builtin.file:
        path: /etc/keepalived
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy fixed keepalived.conf
      ansible.builtin.copy:
        src: "{{ config_src_base }}/keepalived.conf"
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart keepalived

    - name: Ensure keepalived log file exists
      ansible.builtin.file:
        path: /var/log/keepalived.log
        state: touch
        owner: root
        group: root
        mode: '0644'
        modification_time: preserve
        access_time: preserve

    - name: Ensure keepalived service is enabled and running
      ansible.builtin.systemd:
        name: keepalived
        enabled: yes
        state: started

  handlers:
    - name: Restart keepalived
      ansible.builtin.systemd:
        name: keepalived
        state: restarted
