---
- name: Full RHEL 9.7 system setup with BIND
  hosts: svc-1.ocp.lan
  become: true
  gather_facts: true

  vars:
    bind_base: "{{ playbook_dir }}/../config_Files/bind"

  tasks:
    # -------- BIND --------

    - name: Install BIND (named)
      ansible.builtin.dnf:
        name:
          - bind
          - bind-utils
        state: present

    - name: Ensure /var/named directory exists
      ansible.builtin.file:
        path: /var/named
        state: directory
        owner: root
        group: named
        mode: '0755'

    - name: Copy named.conf (main config)
      ansible.builtin.copy:
        src: "{{ bind_base }}/named.conf.options"
        dest: /etc/named.conf
        owner: root
        group: named
        mode: '0644'
        backup: yes

    - name: Ensure /etc/named directory exists
      ansible.builtin.file:
        path: /etc/named
        state: directory
        owner: root
        group: named
        mode: '0755'

    - name: Copy additional named config (local zones)
      ansible.builtin.copy:
        src: "{{ bind_base }}/named.conf.local"
        dest: /etc/named/local.conf
        owner: root
        group: named
        mode: '0644'
        backup: yes

    - name: Copy forward zone file
      ansible.builtin.copy:
        src: "{{ bind_base }}/zones/db.kube.lan"
        dest: /var/named/db.kube.lan
        owner: root
        group: named
        mode: '0644'
        backup: yes

    - name: Copy reverse zone file
      ansible.builtin.copy:
        src: "{{ bind_base }}/zones/db.reverse"
        dest: /var/named/db.reverse
        owner: root
        group: named
        mode: '0644'
        backup: yes

    - name: Ensure correct ownership on zone files
      ansible.builtin.file:
        path: /var/named
        owner: root
        group: named
        recurse: yes

    - name: Touch and set permissions on check_bind.log
      ansible.builtin.file:
        path: /var/log/check_bind.log
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Validate BIND configuration
      ansible.builtin.command: named-checkconf
      register: bind_check
      failed_when: bind_check.rc != 0

    - name: Restart and enable named
      ansible.builtin.service:
        name: named
        state: restarted
        enabled: true
