---
- name: Force Replace Network Configurations (RHEL 9.7) - Network Only
  hosts: svc-1.ocp.lan
  become: true
  gather_facts: false

  vars:
    nm_path: "/etc/sysconfig/network-scripts"
    repo_path: "{{ playbook_dir }}/../config_Files/network-ip"
    network_files:
      - ifcfg-ens160
      - ifcfg-ens192

  tasks:
    - name: Deploy corrected RHEL keyfiles (only overwrite if different)
      ansible.builtin.copy:
        src: "{{ repo_path }}/{{ item }}"
        dest: "{{ nm_path }}/{{ item }}"
        owner: root
        group: root
        mode: "0644"
        backup: true
      loop: "{{ network_files }}"
      notify: Restart Networking

  handlers:
    - name: Restart Networking
      ansible.builtin.shell: |
        nmcli connection reload
        nmcli con up ifname ens160
        nmcli con up ifname ens192
      changed_when: false
