---
- name: Smart Hostname & Network Setup
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    desired_hostname: "svc-1.kube.lan"
    cluster_ip: "10.0.0.11"

  tasks:
    # -------- 1. Hostname Logic --------
    - name: Set system hostname
      ansible.builtin.hostname:
        name: "{{ desired_hostname }}"
      register: hostname_result

    - name: Confirm hostname state
      ansible.builtin.debug:
        msg: "[*] Hostname is correct: {{ desired_hostname }}"
      when: not hostname_result.changed

    # -------- 2. /etc/hosts Logic --------
    - name: Ensure /etc/hosts uses cluster IP for name resolution
      ansible.builtin.lineinfile:
        path: /etc/hosts
        # Remove any existing loopback or old IP entries for this hostname
        regexp: '.*{{ desired_hostname | regex_escape }}$'
        line: "{{ cluster_ip }} {{ desired_hostname }} svc-1"
        owner: root
        group: root
        mode: '0644'
      register: hosts_result

    - name: Notify of /etc/hosts update
      ansible.builtin.debug:
        msg: "[+] /etc/hosts updated: {{ cluster_ip }} -> {{ desired_hostname }}"
      when: hosts_result.changed

    # -------- 3. Connectivity Verification --------
    - name: Verify local resolution
      ansible.builtin.command: "getent hosts {{ desired_hostname }}"
      register: resolution_check
      changed_when: false

    - name: Show resolution status
      ansible.builtin.debug:
        msg: "[✓] Verified: {{ resolution_check.stdout }}"
