---
- name: Idempotent Root Password Setup
  hosts: localhost
  become: true
  gather_facts: false

  vars:
    # We define a static salt. This ensures the hash is identical every run.
    # A salt is just a random string (e.g., 8-16 characters).
    my_static_salt: "mycustomsalt123"
    root_pass: "123"

  tasks:
    - name: Ensure root password is set correctly (Idempotent)
      ansible.builtin.user:
        name: root
        # By adding the second argument to password_hash, the hash stays the same
        password: "{{ root_pass | password_hash('sha512', my_static_salt) }}"
      register: password_update

    - name: Notify password status
      ansible.builtin.debug:
        msg: "[+] Root password has been updated."
      when: password_update.changed

    - name: Confirm password status
      ansible.builtin.debug:
        msg: "[*] Root password is already set correctly. No change needed."
      when: not password_update.changed
