---
- name: RHEL 10.1 Keepalived Setup
  hosts: localhost
  become: true
  gather_facts: false

  vars:
    # Base path for your source config files
    config_src_base: "/root/openShift_Cluster_Config/service_Node_Config/service_Node-01/config_Files/keepalived"

  tasks:
    - name: Install keepalived
      ansible.builtin.dnf:
        name: keepalived
        state: present

    - name: Enable ip_nonlocal_bind sysctl
      ansible.builtin.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: "1"
        state: present
        reload: yes

    - name: Ensure keepalived config directory exists
      ansible.builtin.file:
        path: /etc/keepalived
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy fixed keepalived.conf
      ansible.builtin.copy:
        src: "{{ config_src_base }}/keepalived.conf"
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart keepalived

    - name: Ensure keepalived log file exists
      ansible.builtin.file:
        path: /var/log/keepalived.log
        state: touch
        owner: root
        group: root
        mode: '0644'
        modification_time: preserve
        access_time: preserve

    - name: Deploy health check scripts
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "0755"
      loop:
        - { src: "{{ config_src_base }}/check_bind9/chk_bind.sh", dest: "/usr/local/bin/chk_bind.sh" }
        - { src: "{{ config_src_base }}/check_chrony/chk_chrony.sh", dest: "/usr/local/bin/chk_chrony.sh" }
        - { src: "{{ config_src_base }}/check_dhcp/chk_dhcp.sh", dest: "/usr/local/bin/chk_dhcp.sh" }
        - { src: "{{ config_src_base }}/check_haproxy/chk_haproxy.sh", dest: "/usr/local/bin/chk_haproxy.sh" }
        - { src: "{{ config_src_base }}/check_drbd-nfs/chk_drbd.sh", dest: "/usr/local/bin/chk_drbd.sh" }
        - { src: "{{ config_src_base }}/check_drbd-nfs/ha-backup.sh", dest: "/usr/local/bin/ha-backup.sh" }
        - { src: "{{ config_src_base }}/check_drbd-nfs/ha-master.sh", dest: "/usr/local/bin/ha-master.sh" }
      notify: Restart keepalived

    - name: Ensure keepalived service is enabled and running
      ansible.builtin.systemd:
        name: keepalived
        enabled: yes
        state: started

  handlers:
    - name: Restart keepalived
      ansible.builtin.systemd:
        name: keepalived
        state: restarted
